# Site settings
title: Profile of Vinayak Aggarwal
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aggarwalvinayak.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Vinayak Aggarwal
user_description: I am a second year Computer Science Undergraduate Student at BITS Pilani, Goa Campus.<br/>A enthusiast Competitive Coder and an Open Source Developer. Also having a good experience in the field of MACHINE LEARNING and a beginner in the field of NLP.
user_title: An Aspiring Computer Scientist
email: f20170008@goa.bits-pilani.in
#twitter_username: 
github_username:  aggarwalvinayak
#gplus_username: 

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
